# Generated by Django 4.1.4 on 2023-06-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bid_alter_user_username_listing_comment_bid_bidder"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="starting_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
