# Generated by Django 4.1.4 on 2023-06-16 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_starting_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="auctions.bid",
            ),
        ),
    ]
