# Generated by Django 4.1.4 on 2023-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_listing_current_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing", name="image", field=models.URLField(),
        ),
    ]
