# Generated by Django 4.1.4 on 2023-06-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing_poster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing", name="image", field=models.URLField(null=True),
        ),
    ]
