# Generated by Django 4.1.4 on 2023-06-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_remove_listing_winner_listing_ongoing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="listing",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="auctions.listing",
            ),
            preserve_default=False,
        ),
    ]
